// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-explanation': string;
  'main-section': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
